version: 2.1
jobs:
  build:
    docker: 
      - image: python:3
    steps:
      - checkout 
      - run:
          name: install prerequisites
          command: |
            apt update && apt upgrade -y
            apt install python3-pip -y
            pip3 install -r requirements.txt
            wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
            sh -c 'tar -x geckodriver -zf geckodriver-v0.23.0-linux64.tar.gz -O > /usr/bin/geckodriver'
            chmod +x /usr/bin/geckodriver
            rm geckodriver-v0.23.0-linux64.tar.gz
            apt install firefox-esr -y
      - run: sudo ./scripts/run &; python3 ./scripts/test.py

