version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout 
      - run:
          name: install prerequisites
          command: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install python3.7 -y
            sudo apt install python3-pip -y
            sudo pip3 install -r requirements.txt
            wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
            sudo sh -c 'tar -x geckodriver -zf geckodriver-v0.23.0-linux64.tar.gz -O > /usr/bin/geckodriver'
            sudo chmod +x /usr/bin/geckodriver
            rm geckodriver-v0.23.0-linux64.tar.gz
      - run: python3 ./scripts/test.py
