version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout 
      - run:
          name: install prerequisites
          command: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install python3 -y
            sudo apt install python3-pip -y
            sudo pip3 install -r requirements.txt
            sudo apt install firefox -y
      - run: python3 ./scripts/test.py
